// <auto-generated />
using System;
using CleanArchitecture.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221002223245_AddTabCand")]
    partial class AddTabCand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CleanArchitecture.Core.Entities.Cand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataApauracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("cc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dvt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("n")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pvap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sqcand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("st")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Entities.UrlStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataApauracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("UrlStatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
